#!/bin/bash

set -e

# choco dumps a ton of stuff in the PWD/usr
# This hack will clean it up automatically.
function finish {                                                               
	if [ -d usr ]; then
	        rm -rf usr
	fi
}                                                                               
trap finish EXIT

# Wrap the mono choco.exe command
mono /usr/local/bin/chocolatey/choco.exe "$@" --allow-unofficial
